name: app_data_usage
description: "A Flutter plugin to check daily data usage(both wifi and mobile) for the installed app. Only support for android currently as iOS doesn't allow to query this."
version: 1.0.1
homepage: https://github.com/dmgcoding/app_data_usage
repository: https://github.com/dmgcoding/app_data_usage
issue_tracker: https://github.com/dmgcoding/app_data_usage/issues

environment:
  sdk: ^3.6.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.dmgcoding.app_data_usage
        pluginClass: AppDataUsagePlugin